[package]
name = "coursework-battle-io"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gmeta.workspace = true
gstd.workspace = true
store-io.workspace = true
