[package]
name = "store-battle"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gstd.workspace = true
store-io.workspace = true
sharded-fungible-token-io.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
store-io.workspace = true
